---
- include_tasks: windows.yml
  when: ansible_distribution|regex_search('([mM]icrosoft|[wW]indows)')

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: rhel.yml
  when: ansible_os_family == 'RedHat'
